version: '3.3'
services:
  discord-analytics-backend:
    restart: unless-stopped
    build: discord-analytics-backend
    env_file:
      - .env
    networks:
      - private
  discord-analytics-frontend:
    restart: unless-stopped
    build: discord-analytics-frontend
    networks:
      - private
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    environment:
      - TZ=Europe/Berlin
      - VALIDATION=http
    env_file:
      - .env
    volumes:
      - ./nginx.cfg:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - private
    depends_on:
      - discord-analytics-backend
      - discord-analytics-frontend
networks:
  private:
    driver: 'bridge'
